export default {
    FETCH_GOALS: 'FETCH_GOALS',
    FETCH_GOAL: 'FETCH_GOAL',
    CREATE_GOAL: 'CREATE_GOAL',
    UPDATE_GOAL: 'UPDATE_GOAL',
    FETCH_TASKS: 'FETCH_TASKS',
    FETCH_TASK: 'FETCH_TASK',
    CREATE_TASK: 'CREATE_TASK',
    FETCH_HABITS: 'FETCH_HABITS',
    CREATE_HABIT: 'CREATE_HABIT'
}